# Generated by Django 5.2.12 on 2026-07-21 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('report_time', models.TimeField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['report_date', 'report_time'], name='scraper_pdf_report__711772_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParsedTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_index', models.IntegerField()),
                ('row_index', models.IntegerField()),
                ('row_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_data', to='scraper.pdfdocument')),
            ],
            options={
                'ordering': ['table_index', 'row_index'],
                'unique_together': {('pdf_document', 'table_index', 'row_index')},
            },
        ),
    ]
