# Generated by Django 6.0.7 on 2026-07-23 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedCompanyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('symbol', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('change_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_companies', to='scraper.pdfdocument')),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.DeleteModel(
            name='ParsedTableData',
        ),
    ]
