# Generated by Django 6.0.7 on 2026-07-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_extractedcompanyrecord_delete_parsedtabledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
