# Generated by Django 6.0.7 on 2026-07-25 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_pdfdocument_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('REMOVED', 'REMOVED'), ('EXISTING', 'EXISTING')], max_length=20)),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_results', to='scraper.pdfdocument')),
                ('previous_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_results', to='scraper.pdfdocument')),
            ],
        ),
    ]
