# Generated by Django 6.0.7 on 2026-07-25 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_comparisonresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonresult',
            name='current_pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_comparisons', to='scraper.pdfdocument'),
        ),
        migrations.AlterField(
            model_name='comparisonresult',
            name='previous_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_comparisons', to='scraper.pdfdocument'),
        ),
    ]
