# Generated by Django 5.2.12 on 2026-08-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_generatedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedcompanyrecord',
            name='sector',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
