# Generated by Django 5.2.6 on 2026-08-12 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_extractedcompanyrecord_sector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_market_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extractedcompanyrecord',
            name='volume',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='extractedcompanyrecord',
            index=models.Index(fields=['symbol'], name='scraper_ext_symbol_1e5b47_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedcompanyrecord',
            index=models.Index(fields=['sector'], name='scraper_ext_sector_9769c4_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedcompanyrecord',
            index=models.Index(fields=['pdf_document', 'symbol'], name='scraper_ext_pdf_doc_fa2ce7_idx'),
        ),
    ]
