# Generated by Django 5.2.17 on 2026-08-12 17:11

from django.db import migrations, models
from django.db.models import Count


def remove_duplicate_market_rows(apps, schema_editor):
    """Keep the newest copy of legacy duplicate rows before enforcing integrity."""
    for model_name, fields in (
        ("ExtractedCompanyRecord", ("pdf_document_id", "symbol")),
        ("ComparisonResult", ("current_pdf_id", "symbol")),
    ):
        model = apps.get_model("scraper", model_name)
        duplicates = model.objects.values(*fields).annotate(total=Count("id")).filter(total__gt=1)
        for duplicate in duplicates.iterator():
            lookup = {field: duplicate[field] for field in fields}
            ids = list(model.objects.filter(**lookup).order_by("-id").values_list("id", flat=True))
            model.objects.filter(id__in=ids[1:]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_generatedreport_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_market_rows, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='comparisonresult',
            constraint=models.UniqueConstraint(fields=('current_pdf', 'symbol'), name='unique_comparison_current_pdf_symbol'),
        ),
        migrations.AddConstraint(
            model_name='extractedcompanyrecord',
            constraint=models.UniqueConstraint(fields=('pdf_document', 'symbol'), name='unique_pdf_company_symbol'),
        ),
        migrations.AddConstraint(
            model_name='pdfdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('file_hash__isnull', False), models.Q(('file_hash', ''), _negated=True)), fields=('file_hash',), name='unique_nonempty_pdf_file_hash'),
        ),
    ]
