# Generated by Django 5.2.6 on 2026-08-12 14:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='AlertSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('price_change', 'Price change'), ('watchlist_movement', 'Watchlist movement'), ('volume_movement', 'Volume movement')], max_length=40)),
                ('enabled', models.BooleanField(default=False)),
                ('threshold', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_settings', to='pdfs.clientcompany')),
            ],
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('price_change', 'Price change'), ('watchlist_movement', 'Watchlist movement'), ('volume_movement', 'Volume movement')], max_length=40)),
                ('symbol', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('triggered_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('email_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_history', to='pdfs.clientcompany')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('watchlist_alerts', models.BooleanField(default=True)),
                ('default_market', models.CharField(default='PSX - Pakistan Stock Exchange', max_length=80)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='pdfs.clientcompany')),
            ],
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('pdf_management', 'PDF Management'), ('pdf_upload', 'PDF Upload'), ('pdf_processing', 'PDF Processing'), ('daily_market_explorer', 'Daily Market Explorer'), ('company_analysis', 'Company Analysis'), ('market_comparison', 'Market Comparison'), ('market_analytics', 'Market Analytics'), ('reports', 'Reports'), ('watchlist', 'Watchlist'), ('watchlist_management', 'Watchlist Management'), ('search_screener', 'Search & Screener'), ('alerts', 'Alerts'), ('settings_profile', 'Settings / Profile')], max_length=40)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='pdfs.clientcompany')),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='pdfs.clientcompany')),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.AddIndex(
            model_name='clientcompany',
            index=models.Index(fields=['company_name'], name='pdfs_client_company_c0a92e_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertsetting',
            constraint=models.UniqueConstraint(fields=('company', 'alert_type'), name='unique_company_alert_setting'),
        ),
        migrations.AddIndex(
            model_name='alerthistory',
            index=models.Index(fields=['company', 'created_at'], name='pdfs_alerth_company_57eaea_idx'),
        ),
        migrations.AddIndex(
            model_name='alerthistory',
            index=models.Index(fields=['symbol'], name='pdfs_alerth_symbol_84e18b_idx'),
        ),
        migrations.AddIndex(
            model_name='modulepermission',
            index=models.Index(fields=['company', 'module'], name='pdfs_module_company_04c162_idx'),
        ),
        migrations.AddConstraint(
            model_name='modulepermission',
            constraint=models.UniqueConstraint(fields=('company', 'module'), name='unique_company_module_permission'),
        ),
        migrations.AddIndex(
            model_name='watchlistentry',
            index=models.Index(fields=['company', 'symbol'], name='pdfs_watchl_company_e25d8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='watchlistentry',
            constraint=models.UniqueConstraint(fields=('company', 'symbol'), name='unique_company_watchlist_symbol'),
        ),
    ]
