# Generated by Django 5.2.17 on 2026-08-18 07:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0002_clientcompany_alertsetting_alerthistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('value_difference', 'Value difference'), ('date_occurrence', 'Date occurrence')], max_length=40)),
                ('threshold', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('occurrence_gap_days', models.PositiveIntegerField(default=3)),
                ('comparison_type', models.CharField(choices=[('gte', 'Greater than or equal'), ('absolute', 'Absolute difference')], default='absolute', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_triggered_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('last_triggered_event_key', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['alert_type'],
            },
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='watchlist_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_history', to='pdfs.watchlistentry'),
        ),
        migrations.AddField(
            model_name='watchlistentry',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='watchlistentry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='watchlistentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='watchlistentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='alert_type',
            field=models.CharField(choices=[('price_change', 'Price change'), ('watchlist_movement', 'Watchlist movement'), ('volume_movement', 'Volume movement'), ('value_difference', 'Value difference'), ('date_occurrence', 'Date occurrence')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='watchlistentry',
            index=models.Index(fields=['user', 'symbol'], name='pdfs_watchl_user_id_299153_idx'),
        ),
        migrations.AddConstraint(
            model_name='watchlistentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'symbol'), name='unique_user_active_watchlist_symbol'),
        ),
        migrations.AddField(
            model_name='watchlistalertrule',
            name='watchlist_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='pdfs.watchlistentry'),
        ),
        migrations.AddConstraint(
            model_name='watchlistalertrule',
            constraint=models.UniqueConstraint(fields=('watchlist_entry', 'alert_type'), name='unique_watchlist_entry_alert_type'),
        ),
    ]
